name: Компиляция плагина

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Подключение Java 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: temurin

      - name: Настройка доступа к gradlew
        run: chmod +x ./gradlew

      - name: Сборка плагина в jar
        run: ./gradlew jar

      - name: Выгрузка jar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/
